const Sequelize = require('sequelize')
const db = require('./config')

const User = db.define('user', {
  name: {
    type: Sequelize.STRING,
    allowNull: false
  },
  summonerId: {
    type: Sequelize.INTEGER,
    allowNull: false
  }
})

const Champion = db.define('champion', {
  name: {
    type: Sequelize.STRING,
    allowNull: false
  },
  champId: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  icon: {
    type: Sequelize.STRING,
    allowNull: false
  },
  splash: {
    type: Sequelize.STRING,
    allowNull: false
  },
  desc: {
    type: Sequelize.TEXT,
    allowNull: false
  }
})

User.sync()
Champion.sync({force: true})
  .then(function() {
    console.log('Champion table created...')
    return Champion.bulkCreate([
      {name: 'Aatrox', champId: 266, icon: '/LOLicons/AatroxSquare.png', splash: '/Wallpapers/Aatrox.jpg', desc: "Aatrox is a legendary warrior, one of only five that remain of an ancient race known as the Darkin. He wields his massive blade with grace and poise, slicing through legions in a style that is hypnotic to behold. With each foe felled, Aatrox's seemingly living blade drinks in their blood, empowering him and fueling his brutal, elegant campaign of slaughter."},
      {name: 'Ahri', champId: 103, icon: '/LOLicons/AhriSquare.png', splash: '/Wallpapers/Ahri.jpg', desc: "Innately connected to the latent power of Runeterra, Ahri is a vastaya who can reshape magic into orbs of raw energy. She revels in toying with her prey by manipulating their emotions before devouring their life essence. Despite her predatory nature, Ahri retains a sense of empathy as she receives flashes of memory from each soul she consumes."},
      {name: 'Akali', champId: 84, icon: '/LOLicons/AkaliSquare.png', splash: '/Wallpapers/Akali.jpg', desc: "There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness - all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou and it employs a triumvirate of shadow warriors to uphold its causes in the world. Akali is one of these shadow warriors, entrusted with the sacred duty of Pruning the Tree - eliminating those who threaten the equilibrium of Valoran."},
      {name: 'Alistar', champId: 12, icon: '/LOLicons/AlistarSquare.png', splash: '/Wallpapers/Alistar.jpg', desc: "As the mightiest warrior to ever emerge from the Minotaur tribes of the Great Barrier, Alistar defended his tribe from Valoran's many dangers; that is, until the coming of the Noxian army. Alistar was lured from his village by the machinations of Keiran Darkwill, General Boram Darkwill's youngest son and commander of the Noxian expeditionary force. When Alistar returned, he found his village burning and his family slain. Bellowing with rage, he charged an entire regiment of Noxus' elite, slaughtering them by the hundreds. Only the intervention of some of Noxus' most skilled blood mages checked Alistar's rage. Brought in chains to Noxus, Alistar spent the intervening years as a gladiator in the Fleshing, pitted in endless battle for the entertainment of Noxus' wealthy leaders."},
      {name: 'Amumu', champId: 32, icon: '/LOLicons/AmumuSquare.png', splash: '/Wallpapers/Amumu.jpg', desc: "A lonely and melancholy soul from ancient Shurima, Amumu roams the world in search of a friend. Cursed by an ancient spell, he is doomed to remain alone forever, as his touch is death and his affection ruin. Those who claim to have seen him describe Amumu as a living cadaver, small in stature and covered in bandages the color of lichen. Amumu has inspired myths, folklore, and legends told and retold for generations - such that it is impossible to separate truth from fiction."},
      {name: 'Anivia', champId: 34, icon: '/LOLicons/AniviaSquare.png', splash: '/Wallpapers/Anivia.jpg', desc: "An eternal guardian, the Cryophoenix has held a solitary vigil over the Freljord for a thousand lifetimes. Sensing a growing corruption of the land itself, Anivia joins the Avarosan in the belief that a united Freljord can defeat the coming darkness."},
      {name: 'Annie', champId: 1, icon: '/LOLicons/AnnieSquare.png', splash: '/Wallpapers/Annie.jpg', desc: "Early on, Annie's parents knew there was something special about their daughter. At the age of two, Annie miraculously ensorcelled a shadow bear - a ferocious denizen of the petrified forests outside the colony - turning it into her pet. To this day she keeps her bear 'Tibbers' by her side, often keeping him spellbound as a stuffed doll to be carried like a child's toy. The combination of Annie's lineage and the dark magic of her birthplace have given this little girl tremendous arcane power."},
      {name: 'Ashe', champId: 22, icon: '/LOLicons/AsheSquare.png', splash: '/Wallpapers/Ashe.jpg', desc: "With each arrow she fires from her ancient ice-enchanted bow, Ashe proves she is a master archer. She chooses each target carefully, waits for the right moment, and then strikes with power and precision. It is with this same vision and focus that she pursues her goal of uniting the tribes of the Freljord and forging them into a mighty nation."},
      {name: 'Aurelion Sol', champId: 136, icon: '/LOLicons/Aurelion_SolSquare.png', splash: '/Wallpapers/Aurelion_Sol.jpg', desc: "Aurelion Sol once graced the vast emptiness of the cosmos with celestial wonders of his own devising. Now, he is forced to wield his awesome power at the behest of a space-faring empire that tricked him into servitude. Desiring a return to his star-forging ways, Aurelion Sol will drag the very stars from the sky, if he must, in order to regain his freedom."},
      {name: 'Azir', champId: 268, icon: '/LOLicons/AzirSquare.png', splash: '/Wallpapers/Azir.jpg', desc: "Azir was a mortal emperor of Shurima in a far distant age, a proud man who stood at the cusp of immortality. His hubris saw him betrayed and murdered at the moment of his greatest triumph, but now, millennia later, he has been reborn as an Ascended being of immense power. With his buried city risen from the sand, Azir seeks to restore Shurima to its former glory."},
      {name: 'Bard', champId: 432, icon: '/LOLicons/BardSquare.png', splash: '/Wallpapers/Bard.jpg', desc: "Bard travels through realms beyond the imagination of mortal beings. Some of Valoran's greatest scholars have spent their lives trying to understand the mysteries he embodies. This enigmatic spirit has been given many names throughout the history of Valoran, but titles such as Cosmic Vagabond and Great Caretaker only capture a fleeting aspect of his true purpose. When the unknowable structure of the universe is threatened, Bard steers all existence away from utter annihilation."},
      {name: 'Blitzcrank', champId: 53, icon: '/LOLicons/BlitzcrankSquare.png', splash: '/Wallpapers/Blitzcrank.jpg', desc: "Blitzcrank is an enormous, near-indestructible steam golem originally built to dispose of hazardous waste in Zaun. Evolved beyond his primary purpose, Blitzcrank selflessly uses his strength and durability to protect others. Able to see past false veneers and artifice to the truth of an intention, Blitzcrank moves to help those in need."},
      {name: 'Brand', champId: 63, icon: '/LOLicons/BrandSquare.png', splash: '/Wallpapers/Brand.jpg', desc: "Kegan sailed far and wide with his fellows, stealing treasures from those unlucky enough to catch their attention. To some, he was a monster; to others, just a man. One night, as they sailed through the arctic waters, strange lights danced over the frozen wastes. There was something hypnotic about them; it was something that drew them to it like moths to a flame. Trekking across the frozen waste, they came to a cave covered in ancient runes. The meaning of the runes long lost to them, Kegan led the way inside. There, inside a perfect cage of ice floated a dancing column of flame. There was no way such a thing should be burning, especially not in this place. However, its movement was as hypnotic as a siren's song, captivating and seductive. While the others stayed back, Kegan could not help but approach it while holding out his hand..."},
      {name: 'Braum', champId: 201, icon: '/LOLicons/BraumSquare.png', splash: '/Wallpapers/Braum.jpg', desc: "Blessed with massive muscles, and an even bigger heart, Braum is a beloved hero of the Freljord. Every child born to the ice knows of his legendary strength, capable of felling entire forests of frost-oaks in a single night or rending the very mountains asunder. With a colossal vault door borne across his back as a shield, Braum roams the land as a friend to those in need and a terrible foe of evildoers."},
      {name: 'Caitlyn', champId: 51, icon: '/LOLicons/CaitlynSquare.png', splash: '/Wallpapers/Caitlyn.jpg', desc: "A determined and skilled investigator, Caitlyn is one of the sheriffs of Piltover, the City of Progress. She is a fiercely intelligent woman with a strong sense of justice and a resolute devotion to the law. Armed with a magnificent hextech rifle, Caitlyn is a patient hunter and the bane of criminals throughout her city."},
      {name: 'Camille', champId: 164, icon: '/LOLicons/CamilleSquare.png', splash: '/Wallpapers/Camille.jpg', desc: "Weaponized to execute outside the boundaries of the law, Camille is an elegant and elite operative who ensures the Piltover machine and its Zaunite underbelly run smoothly. Camille's true strength is her adaptability and attention to detail, viewing sloppy technique as an embarrassment that must be put to order. Raised among manners and money, she is the Principal Intelligencer of Clan Ferros, tasked with cutting down her family's darker problems with surgical precision. With a mind as sharp as the blades she bears, Camille's pursuit of superiority through hextech body augmentation has left many to wonder if she is more machine than woman."},
      {name: 'Cassiopeia', champId: 69, icon: '/LOLicons/CassiopeiaSquare.png', splash: '/Wallpapers/Cassiopeia.jpg', desc: "Cassiopeia is a terrifying creature - half woman, half snake - whose slightest glance brings death. The youngest daughter of one of Noxus' most influential families, she was once a beautiful and cunning temptress capable of manipulating the hardest heart. Transformed by the venom of an ancient Shuriman tomb guardian, she continues to serve Noxian interests as she always has, just in a more... visceral way."},
      {name: "Cho'Gath", champId: 31, icon: "/LOLicons/Cho'GathSquare.png", splash: "/Wallpapers/Cho'Gath.jpg", desc: "Cho'Gath, an alien creature of malice and violence, causes all but the most stalwart to cringe in fear. Cho'Gath even appears to feed on its predations, growing and swelling as it gorges itself. Worse yet, the creature is intelligent, perhaps greatly so, hinting at the sentient horror of the Void."},
      {name: 'Corki', champId: 42, icon: '/LOLicons/CorkiSquare.png', splash: '/Wallpapers/Corki.jpg', desc: "What yordles lack in stature, they make up for with industriousness. Corki, the Daring Bombardier, gained his title by test-piloting one of these contributions - the original design for the Reconnaissance Operations Front-Line Copter, an aerial assault vehicle which has become the backbone of the Bandle City Expeditionary Force (BCEF) Together with his squadron - the Screaming Yipsnakes - Corki soars over Valoran, surveying the landscape and conducting aerial acrobatics for the benefit of onlookers below."},
      {name: 'Darius', champId: 122, icon: '/LOLicons/DariusSquare.png', splash: '/Wallpapers/Darius.jpg', desc: "There is no greater symbol of Noxian might than Darius, the nation's most feared and battle-hardened warrior. Orphaned at a young age, Darius had to fight to keep himself and his younger brother alive. By the time he joined the military, he had already developed the strength and discipline of a veteran soldier."},
      {name: 'Diana', champId: 131, icon: '/LOLicons/DianaSquare.png', splash: '/Wallpapers/Diana.jpg', desc: "Bearing her crescent moonblade, Diana fights as a warrior of the Lunari, a faith all but quashed in the lands around Mount Targon. Clad in shimmering armor the color of winter snow at night, she is a living embodiment of the silver moon's power. Imbued with the essence of an Aspect from beyond Targon's towering summit, Diana is no longer wholly human, and struggles to divine her power and purpose in this world."},
      {name: 'Dr. Mundo', champId: 36, icon: '/LOLicons/Dr._MundoSquare.png', splash: '/Wallpapers/Dr_Mundo.jpg', desc: "Utterly insane, unrepentantly homicidal, and horrifyingly purple, Dr. Mundo is what keeps many of Zaun's citizens indoors on particularly dark nights. This monosyllabic monstrosity seems to want nothing more than pain - both the giving of it, and the receiving of it. Wielding his massive meat cleaver as if it were weightless, Mundo is infamous for capturing and torturing dozens of Zaun's citizens for his nefarious 'operations', which seem to have no overall point or goal. He is brutal. He is unpredictable. He goes where he pleases. He is also not, technically, a doctor."},
      {name: 'Draven', champId: 119, icon: '/LOLicons/DravenSquare.png', splash: '/Wallpapers/Draven.jpg', desc: "Unlike his brother Darius, victory in battle was never enough for Draven. He craved recognition, acclaim, and glory. He first sought greatness in the Noxian military, but his flair for the dramatic went severely underappreciated. Thirsting for a method to share 'Draven' with the world, he turned his attention to the prison system. There he carved out the celebrity he desired by turning the tedious affair of executions into a premiere spectacle."},
      {name: 'Ekko', champId: 245, icon: '/LOLicons/EkkoSquare.png', splash: '/Wallpapers/Ekko.jpg', desc: "A prodigy from the rough streets of Zaun, Ekko manipulates time to twist any situation to his advantage. Using his own invention, the Zero Drive, he explores the branching possibilities of reality to craft the perfect moment. Though he revels in this freedom, when there's a threat to his friends he'll do anything to defend them. To outsiders, Ekko seems to achieve the impossible the first time, every time."},
      {name: 'Elise', champId: 60, icon: '/LOLicons/EliseSquare.png', splash: '/Wallpapers/Elise.jpg', desc: "Elise is a deadly predator who dwells in a shuttered, lightless palace, deep in the Immortal Bastion of Noxus. Once she was mortal, the mistress of a once-powerful house, but the bite of a vile spider god transformed her into something beautiful, undying, and utterly inhuman. To maintain her eternal youth, Elise preys upon the innocent, and there are few who can resist her seductions."},
      {name: 'Evelynn', champId: 28, icon: '/LOLicons/EvelynnSquare.png', splash: '/Wallpapers/Evelynn.jpg', desc: "Swift and lethal, Evelynn is one of the most deadly - and expensive - assassins in all of Runeterra. Able to merge with shadows at will, she patiently stalks her prey, waiting for the right moment to strike. While Evelynn is clearly not entirely human, and her heritage remains unclear, it is believed that she hails from the Shadow Isles - though her link with that tortured realm remains shrouded in mystery."},
      {name: 'Ezreal', champId: 81, icon: '/LOLicons/EzrealSquare.png', splash: '/Wallpapers/Ezreal.jpg', desc: "A self-assured explorer with the uncanny ability to find his way out of trouble, Ezreal traverses Runeterra in search of adventure. Armed with a magical gauntlet procured from the ruins of ancient Shurima, he tempts fate daily by seeking out treacherous, uncharted places and daring to untangle the world's most cryptic mysteries."},
      {name: 'Fiddlesticks', champId: 9, icon: '/LOLicons/FiddlesticksSquare.png', splash: '/Wallpapers/Fiddlesticks.jpg', desc: "A ghastly living scarecrow, Fiddlesticks is an abomination who stalks the darkness, wielding a scythe and preying upon the unwary. Aided by a savage murder of crows, Fiddlesticks relishes terrorizing his victims before claiming their lives amid a flurry of feathers and blood splattered beaks."},
      {name: 'Fiora', champId: 114, icon: '/LOLicons/FioraSquare.png', splash: '/Wallpapers/Fiora.jpg', desc: "The most feared duelist in all Valoran, Fiora is as renowned for her brusque manner and cunning mind as she is for the speed of her bluesteel rapier. Born to House Laurent in the Kingdom of Demacia, Fiora took control of the family from her father in the wake of a scandal that nearly destroyed them. House Laurent's reputation was sundered, but Fiora bends her every effort to restore her family's honor and return them to their rightful place among the great and good of Demacia."},
      {name: 'Fizz', champId: 105, icon: '/LOLicons/FizzSquare.png', splash: '/Wallpapers/Fizz.jpg', desc: "Fizz had a habit of sneaking out of the city to look for trouble. In his many adventures he grew to be a powerful fighter with a keen resourcefulness that let him skirt danger with clever ease. One day, Fizz returned to find the city abandoned: his people had vanished, leaving Fizz without a clue to explain their disappearance. With nothing left in the city to keep him, Fizz salvaged an enchanted trident from the ruins and set out alone."},
      {name: 'Galio', champId: 3, icon: '/LOLicons/GalioSquare.png', splash: '/Wallpapers/Galio.jpg', desc: "Outside the gleaming city of Demacia, the stone colossus Galio keeps vigilant watch. Built as a bulwark against enemy mages, he often stands motionless for decades until the presence of powerful magic stirs him to life. Once activated, Galio makes the most of his time, savoring the thrill of a fight and the rare honor of defending his countrymen. But his triumphs are always bittersweet, for the magic he destroys is also his source of re-animation, and each victory leaves him dormant once again."},
      {name: 'Gangplank', champId: 41, icon: '/LOLicons/GangplankSquare.png', splash: '/Wallpapers/Gangplank.jpg', desc: "As unpredictable as he is brutal, the dethroned reaver king known as Gangplank is feared far and wide. Where he goes, death and ruin follow, and such is his infamy and reputation that the merest sight of his black sails on the horizon causes panic among even the hardiest crew."},
      {name: 'Garen', champId: 86, icon: '/LOLicons/GarenSquare.png', splash: '/Wallpapers/Garen.jpg', desc: "Garen is a warrior of Demacia who has devoted his life to defending his kingdom and its ideals. Armed with his magic-resistant armor and broadsword, Garen puts his life on the line for both his nation, and his fellow soldiers."},
      {name: 'Gnar', champId: 150, icon: '/LOLicons/GnarSquare.png', splash: '/Wallpapers/Gnar.jpg', desc: "A primitive yordle born millennia in the past, Gnar is playful, diminutive and cute until his occasional bouts of anger transform him into a massive, violent, and destructive beast. Trapped within a glacier of True Ice, Gnar was frozen for an age before he broke free, emerging to find the world much changed. These new, exotic realms only ignite his delight and curiosity, for where most fear danger, Gnar pounces to meet it head on."},
      {name: 'Gragas', champId: 79, icon: '/LOLicons/GragasSquare.png', splash: '/Wallpapers/Gragas.jpg', desc: "The only thing more important to Gragas than fighting is drinking. His unquenchable thirst for stronger ale has led him in search of the most potent and unconventional ingredients to toss in his still. Impulsive and unpredictable, this rowdy carouser loves cracking kegs as much as cracking heads. Thanks to his strange brews and temperamental nature, drinking with Gragas is always a risky proposition."},
      {name: 'Graves', champId: 104, icon: '/LOLicons/GravesSquare.png', splash: '/Wallpapers/Graves.jpg', desc: "Malcolm Graves is a wanted man in every realm, city-state, and empire he has visited. Tough, strong-willed, and above all relentless, through his life of crime he has amassed (then invariably lost) a small fortune."},
      {name: 'Hecarim', champId: 120, icon: '/LOLicons/HecarimSquare.png', splash: '/Wallpapers/Hecarim.jpg', desc: "Hecarim is an armored colossus who charges from the Shadow Isles at the head of a deathly host of spectral horsemen to hunt the living. A monstrous fusion of man and beast, cursed to ride for eternity, Hecarim revels in slaughter and crushing souls beneath his armored hooves."},
      {name: 'Heimerdinger', champId: 74, icon: '/LOLicons/HeimerdingerSquare.png', splash: '/Wallpapers/Heimerdinger.jpg', desc: "A brilliant yet eccentric yordle scientist, Professor Cecil B. Heimerdinger is lauded as one of the most innovative minds and esteemed inventors Piltover has ever seen. Relentless in his work to the point of neurotic obsession, he is fascinated by mysteries that have confounded his contemporaries for decades, and thrives on answering the universe's most impenetrable questions. Though his theories often appear opaque and esoteric, Heimerdinger believes knowledge should be shared, and is devoted to teaching all who desire it."},
      {name: 'Illaoi', champId: 420, icon: '/LOLicons/IllaoiSquare.png', splash: '/Wallpapers/Illaoi.jpg', desc: "Illaoi's powerful physique is dwarfed only by her indomitable faith. As the prophet of the Great Kraken, she uses a huge, golden idol to rip her foes' spirits from their bodies and shatter their perception of reality. All who challenge the 'Truth Bearer of Nagakabouros' soon discover Illaoi never battles alone - the god of the Serpent Isles fights by her side."},
      {name: 'Irelia', champId: 39, icon: '/LOLicons/IreliaSquare.png', splash: '/Wallpapers/Irelia.jpg', desc: "Unwilling to relinquish her home, Irelia rose at the brink of death, and her father's weapon lifted into the air alongside her. Irelia rushed back to the fore, unfazed by the blade's sudden animation. The weapon danced around her effortlessly, cutting down Noxians as they gaped in horror. The decimated invaders were forced to retreat from the Placidium, and Irelia was appointed Ionia's Captain of the Guard for her brave defense of her homeland."},
      {name: 'Ivern', champId: 427, icon: '/LOLicons/IvernSquare.png', splash: '/Wallpapers/Ivern.jpg', desc: "Ivern Bramblefoot, known to many as the Green Father, is a peculiar half man, half tree who roams Runeterra's forests, cultivating life everywhere he goes. He knows the secrets of the natural world, and holds deep Friend of the friendships with all things that grow, fly, and scuttle. Ivern wanders the wilderness, imparting strange wisdom to any he meets, enriching the forests, and occasionally entrusting loose-lipped butterflies with his secrets."},
      {name: 'Janna', champId: 40, icon: '/LOLicons/JannaSquare.png', splash: '/Wallpapers/Janna.jpg', desc: "Armed with the power of Runeterra's gales, Janna is a mysterious, elemental wind spirit who protects the dispossessed of Zaun. Some believe she was brought into existence by the pleas of Runeterra's sailors who prayed for fair winds as they navigated treacherous waters and braved rough tempests. Her favor and protection has since been called into the depths of Zaun, where Janna has become a beacon of hope to those in need. No one knows where or when she will appear, but more often than not, she's come to help."},
      {name: 'Jarvan IV', champId: 59, icon: '/LOLicons/Jarvan_IVSquare.png', splash: '/Wallpapers/Jarven.jpg', desc: "Prince Jarvan IV comes from a lineage of kings, and is favored to lead Demacia in the next era. Raised to be the paragon of Demacia's greatest virtues, Jarvan IV often struggles with the heavy expectations placed upon him. On the battlefield, he inspires his troops with his fearsome courage and selfless determination, revealing his true strength as a leader of men."},
      {name: 'Jax', champId: 24, icon: '/LOLicons/JaxSquare.png', splash: '/Wallpapers/Jax.jpg', desc: "The self-styled Grandmaster at Arms known as Jax is a mysterious warrior and sometime mercenary renowned for his prowess in combat and biting sarcasm. While exceptionally skilled with virtually every conceivable weapon, he often chooses to fight with a mundane implement, such as a lamppost, in order to give his opponents a sporting chance."},
      {name: 'Jayce', champId: 126, icon: '/LOLicons/JayceSquare.png', splash: '/Wallpapers/Jayce.jpg', desc: "Jayce is a brilliant inventor who has pledged his life to the defense of Piltover and its unyielding pursuit of progress. With his transforming hextech hammer in hand, Jayce uses his strength, courage, and considerable intelligence to protect his hometown. While revered throughout the city as a hero, he hasn't taken well to the attention it brings. Still, Jayce's heart is in the right place, and even those who envy his natural skills are grateful for his protection in the City of Progress."},
      {name: 'Jhin', champId: 202, icon: '/LOLicons/JhinSquare.png', splash: '/Wallpapers/Jhin.jpg', desc: "Jhin is a meticulous criminal psychopath who believes murder is art. Once an Ionian prisoner, but freed by shadowy elements within Ionia's ruling council, the serial killer now works as their cabal's assassin. Using his gun as his paintbrush, Jhin creates works of artistic brutality, horrifying victims and onlookers. He gains a cruel pleasure from putting on his gruesome theater, making him the ideal choice to send the most powerful of messages: terror."},
      {name: 'Jinx', champId: 222, icon: '/LOLicons/JinxSquare.png', splash: '/Wallpapers/Jinx.jpg', desc: "A manic and impulsive criminal from Zaun, Jinx lives to wreak havoc without care for the consequences. With an arsenal of deadly weapons, she unleashes the loudest blasts and brightest explosions to leave a trail of mayhem and panic in her wake. Jinx despises boredom, and gleefully brings her own chaotic brand of pandemonium wherever she goes."},
      {name: 'Kalista', champId: 429, icon: '/LOLicons/KalistaSquare.png', splash: '/Wallpapers/Kalista.jpg', desc: "A specter of wrath and retribution, Kalista is the undying spirit of vengeance, an armored nightmare summoned from the Shadow Isles to hunt deceivers and traitors. The betrayed may cry out in blood to be avenged, but Kalista only answers those whose cause she deems worthy of her skills. Woe betide those who become the focus of Kalista's wrath, for any pact sealed with this grim hunter can only end on the cold fire of her soul-spears."},
      {name: 'Karma', champId: 43, icon: '/LOLicons/KarmaSquare.png', splash: '/Wallpapers/Karma.jpg', desc: "Karma is a woman of indomitable will and unbound spiritual power. She is the soul of Ionia made manifest and an inspiring presence on the battlefield, shielding her allies and turning back her foes. A strong leader torn between tradition and revolution, Karma seeks to protect the peace of Ionia - by force if necessary."},
      {name: 'Karthus', champId: 30, icon: '/LOLicons/KarthusSquare.png', splash: '/Wallpapers/Karthus.jpg', desc: "The harbinger of oblivion, Karthus is an undying spirit whose haunting songs are a prelude to the horror of his nightmarish appearance. The living fear the eternity of undeath, but Karthus sees only beauty and purity in its embrace, a perfect union of life and death. When Karthus emerges from the Shadow Isles, it is to bring the joy of death to mortals as an apostle of the unliving."},
      {name: 'Kassadin', champId: 38, icon: '/LOLicons/KassadinSquare.png', splash: '/Wallpapers/Kassadin.jpg', desc: "Within a decaying cyclopean city, Kassadin found secrets of the kind that he will never share - secrets that made him quake with fear at the visions of things to come that were thrust upon him. The power of the place threatened to consume him forever, but Kassadin took the only route available to him in order to survive - he let the Void inside him. Miraculously, he was able to overcome the alien urges that went with it, and he emerged as something more than human. Though a part of him died that day, he knows that he must protect Valoran from the things scratching at the door, waiting to get in and visit their torments upon the world."},
      {name: 'Katarina', champId: 55, icon: '/LOLicons/KatarinaSquare.png', splash: '/Wallpapers/Katarina.jpg', desc: "Driven by an intense killer instinct, Katarina uses her talents as an assassin for the glory of Noxus, and the continued elevation of her family. While her fervor drives her to ever-greater feats, it can sometimes lead her astray."},
      {name: 'Kayle', champId: 10, icon: '/LOLicons/KayleSquare.png', splash: '/Wallpapers/Kayle.jpg', desc: "In a world far away, where an ancient war still rages, Kayle was a great hero - the strongest of an immortal race committed to destroying evil wherever it could be found. For ten thousand years, Kayle fought tirelessly for her people, wielding her flaming sword forged before time itself. She shielded her delicate features beneath her enchanted armor, the sole remaining masterpiece of an extinct race of craftsmen. Though a beautiful, striking creature, Kayle, now as then, avoids showing her face; war has taken a terrible toll upon her spirit. In her quest for victory, she sometimes would try to lift the wicked up from their morass of evil, but more than often she instead purged those she herself deemed beyond redemption. To Kayle, justice can so often be an ugly thing."},
      {name: 'Kayn', champId: 141, icon: '/LOLicons/KaynSquare.png', splash: '/Wallpapers/Kayn.jpg', desc: "A peerless practitioner of lethal shadow magic, Shieda Kayn battles to achieve his true destiny—to one day lead the Order of the Shadow into a new era of Ionian supremacy. He audaciously wields the sentient darkin weapon Rhaast, undeterred by its creeping corruption of his body and mind. There are only two possible outcomes: either Kayn bends the weapon to his will... or the malevolent blade consumes him completely, paving the way for the destruction of all Runeterra."},
      {name: 'Kennen', champId: 85, icon: '/LOLicons/KennenSquare.png', splash: '/Wallpapers/Kennen.jpg', desc: "There exists an ancient order originating in the Ionian Isles dedicated to the preservation of balance. Order, chaos, light, darkness - all things must exist in perfect harmony for such is the way of the universe. This order is known as the Kinkou and it employs a triumvirate of shadow warriors to uphold its causes in the world. Kennen is one of these shadow warriors, entrusted with the sacred duty of Coursing the Sun - tirelessly conveying the justice of the Kinkou."},
      {name: "Kha'Zix", champId: 121, icon: "/LOLicons/Kha'ZixSquare.png", splash: "/Wallpapers/Kha'Zix.jpg", desc: "A vicious Void predator, Kha'Zix infiltrated Valoran to devour the land's most promising creatures. With each kill he absorbs his prey's strength, evolving to grow more powerful. Kha'Zix hungers most to conquer and consume Rengar, the one beast he considers his equal."},
      {name: 'Kindred', champId: 203, icon: '/LOLicons/KindredSquare.png', splash: '/Wallpapers/Kindred.jpg', desc: "Separate, but never parted, Kindred represents the twin essences of death. Lamb's bow offers a swift release from the mortal realm for those who accept their fate. Wolf hunts down those who run from their end, delivering violent finality within his crushing jaws. Though interpretations of Kindred's nature vary across Runeterra, every mortal must choose the true face of their death."},
      {name: 'Kled', champId: 240, icon: '/LOLicons/KledSquare.png', splash: '/Wallpapers/Kled.jpg', desc: "A warrior as fearless as he is ornery, Kled is a popular folk hero in Noxus. Embodying the furious bravado of his nation, he is an icon beloved by the empire's soldiers, distrusted by its officers, and loathed by the nobility. Tall tales such as 'The Great Hussar', 'The High General Marshal Sergeant', and 'The Mountain Admiral' trace back to the founding of the empire. Many soldiers claim Kled has fought in every campaign the legions have waged, has 'acquired' every military title, and has never once backed down from a fight. Though the veracity of the details is often questionable, one part of his legend is undeniable: charging into battle on his un-trusty steed, Skaarl, Kled fights to protect what's his... and to take whatever he can get."},
      {name: "Kog'Maw", champId: 40, icon: "/LOLicons/Kog'MawSquare.png", splash: "/Wallpapers/Kog'Maw.jpg", desc: "There amongst the haunting ruins of Icathia, Kog'Maw manifested in Valoran with unsettling curiosity. The spark which led him to Runeterra teased him still, urging him gently towards Malzahar. It also encouraged him to familiarize himself with his new environment, to the stark horror of everything he encountered on his journey."},
      {name: 'LeBlanc', champId: 7, icon: '/LOLicons/LeblancSquare.png', splash: '/Wallpapers/LeBlanc.jpg', desc: "Amongst the cults, covens, and secret societies that call this labyrinth their home, LeBlanc, the Deceiver, presides over the Black Rose, a remnant from a lost, yet similarly unscrupulous time in Noxian history. Ruthless and seemingly ageless, LeBlanc and her ilk were a mainstay in Noxian political affairs during the era before the militarization of the Noxian government. In those days, this guild of powerful magicians met in secret to further their hidden agenda, and to hone a craft more subtle than that preferred by those currently in power."},
      {name: 'Lee Sin', champId: 40, icon: '/LOLicons/Lee_SinSquare.png', splash: '/Wallpapers/Lee_Sin.jpg', desc: "Once a promising mage from Ionia, Lee Sin is a blind monk who sought redemption at the Shojin Monastery for a terrible mistake that cost innocent lives. In the midst of the Noxian invasion, his power became one with his flesh in a way none could have foreseen. With burning fists and inhumanly powerful roundhouse kicks, he fights those who dare despoil his homeland."},
      {name: 'Leona', champId: 89, icon: '/LOLicons/LeonaSquare.png', splash: '/Wallpapers/Leona.jpg', desc: "Imbued with the fire of the sun, Leona is a warrior templar of the Solari who defends Mount Targon with her Zenith Blade and Shield of Daybreak. Her skin shimmers with starfire while her eyes burn with the power of the celestial Aspect within her. Armored in gold and bearing a terrible burden of ancient knowledge, Leona brings enlightenment to some, death to others."},
      {name: 'Lissandra', champId: 127, icon: '/LOLicons/LissandraSquare.png', splash: '/Wallpapers/Lissandra.jpg', desc: "Lissandra's magic twists the pure power of ice into something dark and terrible. With the force of her black ice, she does more than freeze - she impales and crushes those who oppose her. To the terrified denizens of the north, she is known only as 'The Ice Witch'. The truth is much more sinister: Lissandra is a corrupter of nature who plots to unleash an ice age on the world."},
      {name: 'Lucian', champId: 236, icon: '/LOLicons/LucianSquare.png', splash: '/Wallpapers/Lucian.jpg', desc: "Lucian wields relic weapons imbued with ancient power and stands a stalwart guardian against the undead. His cold conviction never wavers, even in the face of the maddening horrors he destroys beneath his hail of purifying fire. Lucian walks alone on a grim mission: to purge the spirits of those ensnared in undeath, his eternal beloved among them."},
      {name: 'Lulu', champId: 117, icon: '/LOLicons/LuluSquare.png', splash: '/Wallpapers/Lulu.jpg', desc: "Perhaps more than any other Yordle, Lulu marches to the beat of her own drum. During her youth in Bandle City, she spent most of her time wandering alone in the forest or lost in a daydream. It wasn't that she was antisocial; the day-to-day bustle of Bandle City just couldn't compete with the vibrant world of her imagination. She saw wonder in places most people overlooked. This was how she found Pix, a fae spirit, pretending to be stuck in a birdhouse."},
      {name: 'Lux', champId: 99, icon: '/LOLicons/LuxSquare.png', splash: '/Wallpapers/Lux.jpg', desc: "Luxanna Crownguard is a powerful young light mage from Demacia, an insular realm where magical abilities are viewed with fear and suspicion. Forced to keep her power secret for much of her young life, she grew up fearing discovery and exile, but learned to embrace her magic and covertly wields it in service of her homeland."},
      {name: 'Malphite', champId: 54, icon: '/LOLicons/MalphiteSquare.png', splash: '/Wallpapers/Malphite.jpg', desc: "There is a world of perfect harmony, where all are part of the whole. The Monolith is the essence of all creation, and its denizens are but singular pieces of it. It is beautiful in its symmetry, and in its almost complete lack of uncertainty. The rocky beings that live there know their place and work to fulfill their duties to the fullest extent, functioning almost as a superorganism or hive. Malphite has always strived to live up to his full potential, as his own personal part of the whole, serving the role of a distinguished creature questing to enforce his people's flawless vision of order."},
      {name: 'Malzahar', champId: 90, icon: '/LOLicons/MalzaharSquare.png', splash: '/Wallpapers/Malzahar.jpg', desc: "Many men have gone mad beneath the glare of the Shurima sun, but it was during the night's chilling embrace that Malzahar relinquished his sanity. Malzahar was born a seer, blessed with the gift of prophecy. His talent, though unrefined, promised to be one of Runeterra's greatest boons, but destiny plotted him another course; his sensitivity to the roiling tides of fate allowed other, unwelcome things to tug at his subconscious mind. In his dreams, where the veil of separation is thinnest, a sinister thing beckoned. For some time, Malzahar was able to resist its prodding solicitation, but with each passing night the voice grew louder, or perhaps deeper, until he could withstand the call no more."},
      {name: 'Maokai', champId: 57, icon: '/LOLicons/MaokaiSquare.png', splash: '/Wallpapers/Maokai.jpg', desc: "Maokai is a rageful, towering treant who fights the unnatural horrors of the Shadow Isles. He was twisted into a force of vengeance after a magical cataclysm destroyed his home, surviving undeath only through the waters of life infused within his heartwood. Once a peaceful nature spirit, Maokai now furiously battles to banish the scourge of unlife from the Shadow Isles and restore his home to its former beauty."},
      {name: 'Master Yi', champId: 11, icon: '/LOLicons/Master_YiSquare.png', splash: '/Wallpapers/Master_Yi.jpg', desc: "Through the ancient martial art of Wuju, Master Yi has tempered his body and sharpened his mind until thought and action have become one. Though he chooses to enter into violence as a last resort, the grace and speed with which he wields his blade ensures resolution is always swift. As the last living practitioner of Wuju, Master Yi has devoted his life to finding able pupils to carry on the legacy of his lost people."},
      {name: 'Miss Fortune', champId: 21, icon: '/LOLicons/Miss_FortuneSquare.png', splash: '/Wallpapers/Miss_Fortune.jpg', desc: "Beauty and danger: There are few who can match Miss Fortune in either. One of Bilgewater's most infamous bounty hunters, she built her legend upon a swathe of bullet-riddled corpses and captured ne'er-do-wells. The booming echoes of her twin pistols in the port city's reeking wharfs and scavenger shanties are sure signs of another warrant from the Bounty Board being settled."},
      {name: 'Wukong', champId: 62, icon: '/LOLicons/WukongSquare.png', splash: '/Wallpapers/Wukong.jpg', desc: "Wukong is a vastayan trickster who uses his strength, agility, and intelligence to confuse his opponents and gain the upper hand. After finding a lifelong friend in the warrior known as Master Yi, Wukong became the last student of the ancient martial art known as Wuju. Armed with an enchanted staff, Wukong seeks to prevent Ionia from falling to ruin."},
      {name: 'Mordekaiser', champId: 82, icon: '/LOLicons/MordekaiserSquare.png', splash: '/Wallpapers/Mordekeiser.jpg', desc: "The baleful revenant Mordekaiser is among the most terrifying and hateful spirits haunting the Shadow Isles. He has existed for countless centuries, shielded from true death by necromantic sorcery and the force of his own dark will. Those who dare face Mordekaiser in battle risk a horrific curse: he enslaves his victims' souls to become instruments of destruction."},
      {name: 'Morgana', champId: 25, icon: '/LOLicons/MorganaSquare.png', splash: '/Wallpapers/Morgana.jpg', desc: "Morgana was one who fought against what she perceived as the tyranny of her kind, and for that she was branded 'fallen'. Morgana was not innocent, having plumbed forgotten ways to gather forbidden might to become a powerful mistress of the black arts. This goal was driven by her obsession to defeat the general of the opposition's army - her sister, Kayle."},
      {name: 'Nami', champId: 267, icon: '/LOLicons/NamiSquare.png', splash: '/Wallpapers/Nami.jpg', desc: "A headstrong young vastaya of the seas, Nami uses her mystical Tidecaller's Blessing to reshape the tides and defend her fellow Marai from danger. The first of her kind to leave the ocean and venture onto dry land, Nami faces the unthinkable with grit, determination, and daring mettle."},
      {name: 'Nasus', champId: 75, icon: '/LOLicons/NasusSquare.png', splash: '/Wallpapers/Nasus.jpg', desc: "Nasus is an imposing, jackal-headed Ascended being from ancient Shurima, a heroic figure regarded as a demigod by the people of the desert. Fiercely intelligent, he was a guardian of knowledge and peerless strategist whose wisdom guided the ancient empire of Shurima to greatness for many centuries. After the fall of the empire, he went into self-imposed exile, becoming little more than a legend. Now that the ancient city of Shurima has risen once more, he has returned, determined to ensure it never falls again."},
      {name: 'Nautilus', champId: 111, icon: '/LOLicons/NautilusSquare.png', splash: '/Wallpapers/Nautilus.jpg', desc: "Once, Nautilus was a sailor commissioned to explore the uncharted reaches of the Guardian's Sea. This expedition took him deep into unknown waters where he and his crew found a vast section of black oozing liquid that none of the crew could identify. Though their job was to investigate anything new that they found, no man aboard was willing to brave the murk except Nautilus. Only moments after he donned the hulking diver's suit and climbed over the ship's rail, something lurking in the muck grabbed hold of him. He clung to the side of the ship, but the thing below pulled him fiercely, rocking the entire ship. The other sailors grew afraid and made a terrible decision. As he stared and pleaded for help, they wrenched his grip free of the rail. He tumbled into the ink, grabbing the anchor in futile desperation. Dark tendrils enveloped him and he could do nothing but watch as the dimming outline of his ship faded away. Then everything went black."},
      {name: 'Nidalee', champId: 76, icon: '/LOLicons/NidaleeSquare.png', splash: '/Wallpapers/Nidalle.jpg', desc: "There are few dwellers residing in the blasted and dangerous lands that lie south of the Great Barrier. Much of that world still bears the scars of past Rune Wars, especially the mysterious Kumungu Jungle. There are long-forgotten treasures in these strange places which many risk life and limb to acquire. Nidalee was only a young girl traveling with her treasure-seeking parents when they lost their way in the dense, rainy jungles. The jungle was unforgiving, and she watched her parents suffer agonizing final days as they fell victim to a mysterious and vicious disease."},
      {name: 'Nocturne', champId: 56, icon: '/LOLicons/NocturneSquare.png', splash: '/Wallpapers/Nocturne.jpg', desc: "Before Nocturne, people believed that dreams were figments of their imagination, meaningless images that flashed through the mind when one slept. This belief was put to the test when a rash of sleep-related incidents started afflicting many throughout Runeterra. Some would wake up screaming, terrified and beyond consolation. Some could not fall asleep, slowly going mad as the nights ticked by. Some simply never woke up. Physicians were baffled until a nightmare-stricken man cried out a haunting name from his unconscious state, then stopped breathing. Magical energy arced from the man, and Nocturne appeared."},
      {name: 'Nunu', champId: 20, icon: '/LOLicons/NunuSquare.png', splash: '/Wallpapers/Nunu.jpg', desc: "As unlikely a pair as anyone could find, Nunu and Willump relied on courage and tenacity to drive them through countless troubles in the Freljord. The boy and his Yeti searched far and wide for a place they'd both be welcome, and eventually found a home among the Avarosan."},
      {name: 'Olaf', champId: 2, icon: '/LOLicons/OlafSquare.png', splash: '/Wallpapers/Olaf.jpg', desc: "Most men would say that death is a thing to be feared; none of those men would be Olaf. The Berserker lives only for the roar of a battle cry and the clash of steel. Spurred on by his hunger for glory and the looming curse of a forgettable death, Olaf throws himself into every fight with reckless abandon. Surrendering to the bloodlust deep within his being, Olaf is only truly alive when grappling with the jaws of death."},
      {name: 'Orianna', champId: 61, icon: '/LOLicons/OriannaSquare.png', splash: '/Wallpapers/Orianna.jpg', desc: "Orianna is a technical marvel comprised entirely of clockwork, but it was not always so - she was once a girl of flesh and blood. As a young child in Piltover, Orianna fell ill, and her dying organs were replaced with elaborate prosthetics until she became the first fully mechanized person. Her closest companion is the mechanical ball she created to serve as her protector and friend. Introspective and curious about her place in the world, Orianna seeks her true purpose."},
      {name: 'Pantheon', champId: 80, icon: '/LOLicons/PantheonSquare.png', splash: '/Wallpapers/Pantheon.jpg', desc: "The peerless warrior known as Pantheon is a nigh-unstoppable paragon of battle. He was born among the Rakkor, a warlike people living on the flanks of Mount Targon, and after climbing the mountain's treacherous peak and being deemed worthy, he was chosen to become the earthly incarnation of the celestial Aspect of War. Imbued with inhuman power, he relentlessly seeks the enemies of Targon, leaving only corpses in his wake."},
      {name: 'Poppy', champId: 78, icon: '/LOLicons/PoppySquare.png', splash: '/Wallpapers/Poppy.jpg', desc: "Runeterra has no shortage of valiant champions, but few are as tenacious as Poppy. Bearing a hammer twice the length of her body, this determined yordle has spent untold years searching for the 'Hero of Demacia', a fabled warrior said to be the rightful wielder of her weapon."},
      {name: 'Quinn', champId: 133, icon: '/LOLicons/QuinnSquare.png', splash: '/Wallpapers/Quinn.jpg', desc: "Quinn is an elite ranger-knight of Demacia who undertakes dangerous missions deep in enemy territory with her legendary eagle, Valor. The two share an unbreakable bond that is uniquely deadly, and their foes are often slain before they realize they are fighting not one, but two Demacian heroes."},
      {name: 'Rakan', champId: 497, icon: '/LOLicons/RakanSquare.png', splash: '/Wallpapers/Rakan.jpg', desc: "As mercurial as he is charming, Rakan is an infamous vastayan troublemaker and the greatest battle-dancer in Lhotlan tribal history. To the humans of the Ionian highlands, his name has long been synonymous with wild festivals, uncontrollable parties, and anarchic music. Few would suspect this energetic, traveling showman is also partner to the rebel Xayah, and is dedicated to her cause."},
      {name: 'Rammus', champId: 33, icon: '/LOLicons/RammusSquare.png', splash: '/Wallpapers/Rammus.jpg', desc: "Idolized by many, dismissed by some, mystifying to all, the curious being, Rammus, is an enigma. Protected by a Spiked Shell, Rammus inspires increasingly disparate theories on his origin wherever he goes - from demigod, to sacred oracle, to a mere beast transformed by magic. Whatever the truth may be, Rammus keeps his own counsel and stops for no one as he roams the desert."},
      {name: "Rek'Sai", champId: 421, icon: "/LOLicons/Rek'SaiSquare.png", splash: "/Wallpapers/Rek'Sai.jpg", desc: "The largest and fiercest of her species, Rek'Sai is a merciless predator that tunnels through the earth to ambush and devour her prey. Her insatiable hunger has laid waste to entire regions of the once-great Shuriman empire. Merchants, traders and armed caravans will go hundreds of miles out of their way to avoid these vast areas, though cunning bandits have been known to lure the unwary into her killing grounds. Once Rek'Sai detects you, your fate is sealed. There is no hope of escape; she is death from below the sand."},
      {name: 'Renekton', champId: 58, icon: '/LOLicons/RenektonSquare.png', splash: '/Wallpapers/Renekton.jpg', desc: "Renekton is a terrifying, rage-fueled Ascended being from the scorched deserts of Shurima. Once, he was his empire's most esteemed warrior, leading the armies of Shurima to countless victories. However, after the empire's fall, Renekton was entombed beneath the sands, and slowly, as the world turned and changed, he succumbed to insanity. Now free once more, he is utterly consumed with finding and killing his brother, Nasus, who he blames, in his madness, for the centuries he spent in darkness."},
      {name: 'Rengar', champId: 107, icon: '/LOLicons/RengarSquare.png', splash: '/Wallpapers/Rengar.jpg', desc: "Rengar is a ferocious vastayan trophy hunter who lives for the thrill of tracking down and killing dangerous creatures. He scours the world for the most fearsome beasts he can find, especially seeking any trace of Kha'Zix, the Void creature who scratched out his eye. Rengar stalks his prey neither for food nor glory, but for the sheer beauty of the pursuit."},
      {name: 'Riven', champId: 92, icon: '/LOLicons/RivenSquare.png', splash: '/Wallpapers/Riven.jpg', desc: "Riven became a leader amongst her peers, a poster child of the Noxian spirit. So exceptional was her passion that the High Command recognized her with a black stone rune sword forged and enchanted with Noxian sorcery. The weapon was heavier than a kite shield and nearly as broad - perfectly suited to her tastes. Soon after, she was deployed to Ionia as part of the Noxian invasion."},
      {name: 'Rumble', champId: 68, icon: '/LOLicons/RumbleSquare.png', splash: '/Wallpapers/Rumble.jpg', desc: "Even amongst yordles, Rumble was always the runt of the litter. As such, he was used to being bullied. In order to survive, he had to be scrappier and more resourceful than his peers. He developed a quick temper and a reputation for getting even, no matter who crossed him. This made him something of a loner, but he didn't mind. He liked to tinker, preferring the company of gadgets, and he could usually be found rummaging through the junkyard."},
      {name: 'Ryze', champId: 13, icon: '/LOLicons/RyzeSquare.png', splash: '/Wallpapers/Ryze.jpg', desc: "Widely considered one of the most adept sorcerers on Runeterra, Ryze is an ancient, hard-bitten archmage with an impossibly heavy burden to bear. Armed with immense arcane power and a boundless constitution, he tirelessly hunts for World Runes - fragments of the raw magic that once shaped the world from nothingness. He must retrieve these glyphs before they fall into the wrong hands, for Ryze understands the horrors they could unleash on Runeterra."},
      {name: 'Sejuani', champId: 113, icon: '/LOLicons/SejuaniSquare.png', splash: '/Wallpapers/Sejuani.jpg', desc: "Sejuani was weaned on hardship and reared on barbarity. Where others succumbed to the harshness of the Freljord, she was tempered by it until pain became power, hunger an encouragement, and frost an ally in culling the weak. Through her ordeals, she learned that to thrive in the endless winter, one must become just as cold and unforgiving. In Sejuani's eyes, her followers either have the mettle to endure or the right to die. Once she has conquered the Freljord, she knows that those who survive will form a nation to be feared."},
      {name: 'Shaco', champId: 35, icon: '/LOLicons/ShacoSquare.png', splash: '/Wallpapers/Shaco.jpg', desc: "Most would say that death isn't funny. It isn't, unless you're Shaco - then it's hysterical. He is Valoran's first fully functioning homicidal comic; he jests until someone dies, and then he laughs. The figure that has come to be known as the Demon Jester is an enigma. No one fully agrees from whence he came, and Shaco never offers any details on his own. A popular belief is that Shaco is not of Runeterra - that he is a thing from a dark and twisted world. Still others believe that he is the demonic manifestation of humanity's dark urges and therefore cannot be reasoned with. The most plausible belief is that Shaco is an assassin for hire, left to his own lunatic devices until his services are needed. Shaco certainly has proven himself to be a cunning individual, evading authorities at every turn who might seek him for questioning for some horrendous, law-breaking atrocity. While such scuttlebutt might reassure the native inhabitants of Valoran, it seems unimaginable that such a malevolent figure is allowed to remain at large."},
      {name: 'Shen', champId: 98, icon: '/LOLicons/ShenSquare.png', splash: '/Wallpapers/Shen.jpg', desc: "Leader of a secret clan of mystic warriors, Shen serves as the Eye of Twilight, entrusted to enforce equilibrium in the world. Longing to remain free from the confusion of emotion, prejudice, or ego, Shen continually struggles, spirit blade in hand, to walk the unseen path of dispassionate judgment."},
      {name: 'Shyvana', champId: 102, icon: '/LOLicons/ShyvanaSquare.png', splash: '/Wallpapers/Shyvana.jpg', desc: "Shyvana is a half-dragon with the magic of a fiery rune shard burning within her heart. Though she often appears humanoid, she can transform into a fearsome dragon at will. Unsure if she is fundamentally human or beast, Shyvana fights to master her powers as she shifts between two forms."},
      {name: 'Singed', champId: 27, icon: '/LOLicons/SingedSquare.png', splash: '/Wallpapers/Singed.jpg', desc: "Singed is a deranged chemist from Zaun who is as brilliant as he is amoral. A child prodigy, he taught himself the ways of chem-tech and biological experimentation, constantly testing the boundaries of conventional science. For over a century, he has continued to refine his art, having extended the natural span of his life through a mix of volatile chemicals and extensive self-performed surgery. He lets nothing - not morality, and certainly not other people - come between him and the knowledge he seeks."},
      {name: 'Sion', champId: 14, icon: '/LOLicons/SionSquare.png', splash: '/Wallpapers/Sion.jpg', desc: "A blood-soaked Noxian war hero from a bygone era, Sion was denied oblivion and brought back so that he may continue to serve the empire even in death. An unstoppable behemoth, he is unleashed on the enemies of Noxus, smashing friends and foes aside as he plows into the heart of the slaughter, hacking and killing at will."},
      {name: 'Sivir', champId: 15, icon: '/LOLicons/SivirSquare.png', splash: '/Wallpapers/Sivir.jpg', desc: "Sivir is a renowned fortune hunter and mercenary captain who plies her trade in the deserts of Shurima. Armed with her legendary jeweled crossblade, she has fought and won countless battles for those who can afford her exorbitant price. Known for her fearless resolve and endless ambition, she prides herself on recovering buried treasures from the perilous tombs of Shurima - for a generous bounty. With ancient forces stirring the very bones of Shurima, Sivir finds herself torn between conflicting destinies."},
      {name: 'Skarner', champId: 72, icon: '/LOLicons/SkarnerSquare.png', splash: '/Wallpapers/Skarner.jpg', desc: "Skarner is an immense crystalline scorpion from a hidden valley in Shurima. Part of the ancient Brackern race, Skarner and his kin are known for their great wisdom and deep connection to the land, as their souls are fused with powerful life crystals which hold the living thoughts and memories of their ancestors. In an age long past, the Brackern entered hibernation to avoid untold magical destruction, but recent, threatening events have roused Skarner. As the only Brackern awake, he strives to protect his kind from those who seek to harm them."},
      {name: 'Sona', champId: 37, icon: '/LOLicons/SonaSquare.png', splash: '/Wallpapers/Sona.jpg', desc: "In secret, Sona discovered a potent and deadly use for her etwahl, using its vibrations to slice objects from a distance. She honed this discipline in private, mastering her gift, that she might be prepared should a fitting recital require the harmony of her talents."},
      {name: 'Soraka', champId: 16, icon: '/LOLicons/SorakaSquare.png', splash: '/Wallpapers/Soraka.jpg', desc: "A healer gifted with the magic of the stars, Soraka holds all living creatures close to her heart. She was once a celestial being, but she sacrificed her immortality and entered the world of mortals. So long as evil threatens life in Valoran, Soraka will not allow herself peace."},
      {name: 'Swain', champId: 50, icon: '/LOLicons/SwainSquare.png', splash: '/Wallpapers/Swain.jpg', desc: "A cunning strategist, Swain was decorated after every battle he fought, regularly hobbling in contemplation at the front of the assault. His rise to power seemed unceasing until he was suddenly removed from the order of battle prior to the Ionian Invasion - a bewildering decision which reeked of bureaucratic subversion. If Swain was upset by the events which unfolded, he never revealed it. His face was so implacable that it was popularly rumored to be a mask, disguising something utterly inhuman beneath. More controversy surrounded the bird that never left his shoulder, whose name he whispered only to it."},
      {name: 'Syndra', champId: 134, icon: '/LOLicons/SyndraSquare.png', splash: '/Wallpapers/Syndra.jpg', desc: "Born with immense magical potential, Syndra loves nothing more than exercising the incredible power at her command. With each passing day, her mastery of magical force grows more potent and devastating. Refusing any notion of balance or restraint, Syndra wants only to retain control of her power, even if it means annihilating the authorities that seek to stop her."},
      {name: 'Tahm Kench', champId: 223, icon: '/LOLicons/Tahm_KenchSquare.png', splash: '/Wallpapers/Tahm_Kench.jpg', desc: "Tahm Kench travels Runeterra's waterways, feeding his insatiable appetite with the misery of the unsuspecting. The singularly charming gourmand savors every moment of his victims' suffering. A deal with Two-Coats may carry you to wherever you wish, but your journey will most assuredly end in the depths of despair."},
      {name: 'Taliyah', champId: 163, icon: '/LOLicons/TaliyahSquare.png', splash: '/Wallpapers/Taliyah.jpg', desc: "Taliyah is a nomadic mage from Shurima who weaves stone with energetic enthusiasm and raw determination. Torn between teenage wonder and adult responsibility, she has crossed nearly all of Valoran on a journey to learn the true nature of her growing powers. Compelled by rumors of the rise of a long-dead emperor, she returns to protect her tribe from dangers uncovered by Shurima's shifting sands. Some have mistaken her tender heart for weakness and paid the price for their error, for beneath Taliyah's youthful demeanor is a will strong enough to move mountains, and a spirit fierce enough to make the earth tremble."},
      {name: 'Talon', champId: 91, icon: '/LOLicons/TalonSquare.png', splash: '/Wallpapers/Talon.jpg', desc: "Talon's earliest memories are the darkness of Noxus' underground passages and the reassuring steel of a blade. He remembers no family, warmth, or kindness. Instead, the clink of stolen gold and the security of a wall at his back are all the kinship he has ever craved. Kept alive only by his quick wits and deft thievery, Talon scraped out a living in the seedy underbelly of Noxus. His mastery of the blade quickly marked him as a threat, and Noxian guilds sent assassins to him with a demand: join their ranks or be killed. He left the bodies of his pursuers dumped in Noxus' moat as his response."},
      {name: 'Taric', champId: 44, icon: '/LOLicons/TaricSquare.png', splash: '/Wallpapers/Taric.jpg', desc: "Taric is the Aspect of the Protector, wielding incredible power as Runeterra's guardian of life, love, and beauty. Shamed by a dereliction of duty and exiled from his homeland Demacia, Taric ascended Mount Targon to find redemption, only to discover a higher calling among the stars. Imbued with the might of ancient Targon, the Shield of Valoran now stands ever vigilant against the insidious corruption of the Void."},
      {name: 'Teemo', champId: 17, icon: '/LOLicons/TeemoSquare.png', splash: '/Wallpapers/Teemo.jpg', desc: "Teemo is a legend among his yordle brothers and sisters in Bandle City. As far as yordles are concerned, there is something just slightly off about him. While Teemo enjoys the companionship of other yordles, he also insists on frequent solo missions in the ongoing defense of Bandle City. Despite his genuinely warm personality, something switches off inside Teemo's mind during combat so that the lives he must end while on patrol do not burden him. Even as a young recruit, the drill instructors and other trainees found it a little disconcerting that, while Teemo was normally charming and kind, he turned deadly serious and highly efficient the minute combat exercises began. Teemo's superiors quickly steered him toward the Scouts of the Mothership, which is one of Bandle City's most distinguished Special Forces unit alongside the Megling Commandos."},
      {name: 'Thresh', champId: 412, icon: '/LOLicons/ThreshSquare.png', splash: '/Wallpapers/Thresh.jpg', desc: "Sadistic and cunning, Thresh is a restless spirit who prides himself on tormenting mortals and breaking them with slow, excruciating inventiveness. His victims suffer far beyond the point of death, for Thresh wreaks agony upon their souls, imprisoning them in his lantern to torture for all eternity."},
      {name: 'Tristana', champId: 18, icon: '/LOLicons/TristanaSquare.png', splash: '/Wallpapers/Tristana.jpg', desc: "Greatness comes in all shapes and sizes, as proven by this diminutive, cannon-wielding yordle. In a world fraught with turmoil, Tristana refuses to back down from any challenge. She represents the pinnacle of martial proficiency, unwavering courage, and boundless optimism. For Trist and her gun, Boomer, every mission is a chance to prove that heroes do exist."},
      {name: 'Trundle', champId: 48, icon: '/LOLicons/TrundleSquare.png', splash: '/Wallpapers/Trundle.jpg', desc: "Trundle is a hulking and devious troll with a mischievous streak. There is nothing he can't beat into submission and bend to his will, not even the ice itself. With his massive, frozen club, he chills his enemies to the core and runs them through with jagged shards of ice. Fiercely territorial, Trundle chases down anyone foolish enough to enter his domain and laughs as they bleed into the tundra."},
      {name: 'Tryndamere', champId: 23, icon: '/LOLicons/TryndamereSquare.png', splash: '/Wallpapers/Tryndamere.jpg', desc: "Fueled by his unbridled fury and rage, Tryndamere cuts his way through the tundra, mastering the art of battle by challenging the Freljord's greatest warriors. The wrathful barbarian seeks revenge on the one who decimated his clan and strikes down all those who stand between him and his final retribution."},
      {name: 'Twisted Fate', champId: 4, icon: '/LOLicons/Twisted_FateSquare.png', splash: '/Wallpapers/Twisted_Fate.jpg', desc: "Twisted Fate is an infamous card shark and swindler who has gambled and charmed his way across much of the known world, earning the enmity and admiration of the rich and foolish alike. He rarely takes things seriously, greeting each day with a mocking smile and an insouciant swagger. In every possible way, Twisted Fate always has an ace up his sleeve."},
      {name: 'Twitch', champId: 29, icon: '/LOLicons/TwitchSquare.png', splash: '/Wallpapers/Twitch.jpg', desc: "A plague rat by birth, a connoisseur of filth by passion, Twitch is a paranoid and mutated rat that walks upright and roots through the dregs of Zaun for treasures only he truly values. Armed with a chem-powered crossbow, Twitch is not afraid to get his paws dirty as he builds a throne of refuse in his kingdom of filth, endlessly plotting the downfall of humanity."},
      {name: 'Udyr', champId: 77, icon: '/LOLicons/UdyrSquare.png', splash: '/Wallpapers/Udyr.jpg', desc: "Udyr is more than a man; he is a vessel for the untamed power of four primal animal spirits. When tapping into the spirits' bestial natures, Udyr can harness their unique strengths: the tiger grants him speed and ferocity, the turtle resilience, the bear might, and the phoenix its eternal flame. With their combined power, Udyr can turn back all those who would attempt to harm the natural order."},
      {name: 'Urgot', champId: 6, icon: '/LOLicons/UrgotSquare.png', splash: '/Wallpapers/Urgot.jpg', desc: "Once a powerful Noxian headsman, Urgot was betrayed by the empire for which he had killed so many. Bound in iron chains, he was forced to learn the true meaning of strength in the Dredge—a prison mine deep beneath Zaun. Emerging in a disaster that spread chaos throughout the city, he now casts an imposing shadow over its criminal underworld. Raising his victims on the very chains that once enslaved him, he will purge his new home of the unworthy, making it a crucible of pain."},
      {name: 'Varus', champId: 110, icon: '/LOLicons/VarusSquare.png', splash: '/Wallpapers/Varus.jpg', desc: "For his incomparable skill with the bow and his unquestioned sense of honor, Varus was chosen to be the warden of a sacred Ionian temple. The temple was built to contain an ancient pit of corruption so vile that Ionian Elders feared it could envelop the island in darkness. Varus prided himself on his position, as only the most exceptional Ionian warriors were selected for the role. He lived with his family in a nearby village and led a quiet life of disciplined routine until the day the forces of Noxus invaded Ionia. Their shock troops left nothing but death and desolation in their wake, and the temple lay in their path. Varus was forced to make a decision. He was bound by honor to stay and defend the temple, but without him the village's few inhabitants could offer little resistance against the oncoming war machine. Gravely, he chose to fulfill his duty as a warden. The corruption could not be allowed to escape."},
      {name: 'Vayne', champId: 67, icon: '/LOLicons/VayneSquare.png', splash: '/Wallpapers/Vayne.jpg', desc: "Shauna Vayne is a deadly, remorseless monster hunter who has pledged her life to finding and killing the demon who murdered her family. Armed with her wrist-mounted crossbows and a heart full of vengeance, Vayne is only truly happy when she's slaying practitioners or creations of the dark arts."},
      {name: 'Veigar', champId: 45, icon: '/LOLicons/VeigarSquare.png', splash: '/Wallpapers/Veigar.jpg', desc: "To most, thoughts of yordles do not conjure images to be feared. The easygoing half-pint race, though fierce, is often regarded with some degree of joviality. Their high-pitched voices and naturally cute forms inspire something of a protective instinct in the larger races, or at least bring to mind images of children playing at being adults. Every now and again, however, a yordle turns so bad that even at its small stature it strikes terror into the hearts of others. Veigar is one such twisted yordle. As a master of the magical black arts, as well as a corrupter of cosmic energy, he is one of the most powerful sorcerers on Valoran."},
      {name: "Vel'Koz", champId: 161, icon: "/LOLicons/Vel'KozSquare.png", splash: "/Wallpapers/Vel'Koz.jpg", desc: "A tentacled horror of the Void, Vel'Koz explores Runeterra with singular purpose: to absorb all knowledge. With his unceasing gaze, Vel'Koz fires disintegrating beams that obliterate and analyze all in his path, feeding him vast quantities of information. None know why he requires such material, though some speculate he seeks to understand Runeterra in order to hasten its ruin."},
      {name: 'Vi', champId: 254, icon: '/LOLicons/ViSquare.png', splash: '/Wallpapers/Vi.jpg', desc: "Once a criminal from the mean streets of Zaun, Vi is a hotheaded, impulsive, and fearsome woman with only a very loose respect for authority figures. Growing up all but alone, Vi developed finely honed survival instincts as well as a wickedly abrasive sense of humor. Now working with the Wardens of Piltover to keep the peace, she wields mighty hextech gauntlets that can punch through walls and suspects with equal ease."},
      {name: 'Viktor', champId: 112, icon: '/LOLicons/ViktorSquare.png', splash: '/Wallpapers/Viktor.jpg', desc: "The herald of a new age of technology, Viktor has devoted his life to the advancement of humankind. An idealist who seeks to lift people to a new level of understanding, he believes that only by embracing a glorious evolution of technology can humanity's full potential be realized. With a body augmented by steel and science, Viktor is zealous in his pursuit of this bright future."},
      {name: 'Vladimir', champId: 8, icon: '/LOLicons/VladimirSquare.png', splash: '/Wallpapers/Vladimir.jpg', desc: "There is a temple hidden in the mountains between Noxus and the Tempest Flats, where the secrets of an ancient and terrifying sorcery are kept. The area surrounding the temple is littered with the exsanguinated corpses of those who have mistakenly wandered too close. These served only to pique the curiosity of Vladimir, when - in his youth - he trekked through these mountains during his flight from Noxus. A day earlier, the teenaged Vladimir had brutally murdered two boys his age, for no better reason than to enjoy the intoxicating scarlet bloom that surged forth. He realized immediately that he would never be able to suppress his murderous desires, and if he remained in Noxus, his foul deeds were sure to catch up with him. Without hesitation, he abandoned the city-state, and journeyed south."},
      {name: 'Volibear', champId: 106, icon: '/LOLicons/VolibearSquare.png', splash: '/Wallpapers/Volibear.jpg', desc: "The unforgiving northern reaches of the Freljord are home to the Ursine, a fierce and warlike race that has endured the barren tundra for thousands of years. Their leader is a furious adversary who commands the force of lightning to strike fear within his foes: Volibear. Both a warrior and a mystic, Volibear seeks to defend the ancient ways and the warrior spirit of his tribe."},
      {name: 'Warwick', champId: 19, icon: '/LOLicons/WarwickSquare.png', splash: '/Wallpapers/Warwick.jpg', desc: "Warwick is a monster who hunts the gray alleys of Zaun. Transformed by agonizing experiments, his body is fused with an intricate system of chambers and pumps, machinery filling his veins with alchemical rage. Bursting out of the shadows, he preys upon those criminals who terrorize the city's depths. Warwick is drawn to blood, and driven mad by its scent. None who spill it can escape him."},
      {name: 'Xayah', champId: 498, icon: '/LOLicons/XayahSquare.png', splash: '/Wallpapers/Xayah.jpg', desc: "Deadly and precise, Xayah is a vastayan revolutionary waging a personal war to save her people. She uses her speed, guile, and razor-sharp feather blades to cut down anyone who stands in her way. Xayah fights alongside her partner and lover, Rakan, to protect their dwindling tribe and restore their race to her vision of its former glory."},
      {name: 'Xerath', champId: 101, icon: '/LOLicons/XerathSquare.png', splash: '/Wallpapers/Xerath.jpg', desc: "Xerath is an Ascended Magus of ancient Shurima, a being of arcane energy writhing in the broken shards of a magical sarcophagus. For millennia, he was trapped beneath the desert sands, but the rise of Shurima freed him from his ancient prison. Driven insane with power, he now seeks to take what he believes is rightfully his and replace the upstart civilizations of the world with one fashioned in his image."},
      {name: 'Xin Zhao', champId: 5, icon: '/LOLicons/Xin_ZhaoSquare.png', splash: '/Wallpapers/Xin_Zhao.jpg', desc: "Whenever Jarvan III, the king of Demacia, delivers one of his rallying speeches from the glinting marble balcony atop the royal palace, Xin Zhao is at his side. Coined the Seneschal of Demacia, Xin Zhao is the personal steward of the Lightshield dynasty. His enigmatic, silent vigil has led to an abundance of conjecture concerning his 'secret life' and origins. Whether it's 'Zaun double-agent' tendered at the dinner table or 'indebted rune mage' mused in the editorials of the 'Demacian Constant', Xin Zhao betrays no hints to sate the curiosity of the masses... for good reason."},
      {name: 'Yasuo', champId: 157, icon: '/LOLicons/YasuoSquare.png', splash: '/Wallpapers/Yasuo.jpg', desc: "Yasuo is a man of resolve, an agile swordsman who wields the wind itself to cut down his foes. This once-proud warrior has been disgraced by a false accusation and forced into a desperate fight for survival. With the world turned against him, he will do everything in his power to bring the guilty to justice and restore his honor."},
      {name: 'Yorick', champId: 83, icon: '/LOLicons/YorickSquare.png', splash: '/Wallpapers/Yorick.jpg', desc: "The last survivor of a long-forgotten religious order, Yorick is both blessed and cursed with power over the dead. Trapped on the Shadow Isles, his only companions are the rotting corpses and shrieking spirits that he gathers to him. Yorick's monstrous actions belie his noble purpose: to free his home from the curse of the Ruination."},
      {name: 'Zac', champId: 154, icon: '/LOLicons/ZacSquare.png', splash: '/Wallpapers/Zac.jpg', desc: "Zac is the product of a toxic spill that ran through a chemtech seam and pooled in an isolated cavern deep in Zaun's Sump. Despite such humble origins, Zac has grown from primordial ooze into a thinking being who dwells in the city's pipes, occasionally emerging to help those who cannot help themselves or to rebuild the broken infrastructure of Zaun."},
      {name: 'Zed', champId: 238, icon: '/LOLicons/ZedSquare.png', splash: '/Wallpapers/Zed.jpg', desc: "Zed is the first ninja in 200 years to unlock the ancient, forbidden ways. He defied his clan and master, casting off the balance and discipline that had shackled him all his life. Zed now offers power to those who embrace knowledge of the shadows, and slays those who cling to ignorance."},
      {name: 'Ziggs', champId: 115, icon: '/LOLicons/ZiggsSquare.png', splash: '/Wallpapers/Ziggs.jpg', desc: "The Piltover military tracked the captives to a Zaunite prison, but their weapons were incapable of destroying the fortified walls. Determined to outdo them, Ziggs began experimenting on a new kind of armament, and quickly realized that he could harness his accidental gift for demolition to save the captured yordles."},
      {name: 'Zilean', champId: 26, icon: '/LOLicons/ZileanSquare.png', splash: '/Wallpapers/Zilean.jpg', desc: "A mystical disease granted Zilean immortality, but detached his consciousness from its anchor in the present time. He now mentally drifts through time, from any point he has already lived to the present, unable to impact the events which unfold. The most torturous aspect of this curse is that Zilean sometimes experiences Urtistan as it once was and the rest of the time resides in its lonely ruins. Zilean quests for a cure, and thereafter a way to save his people."},
      {name: 'Zyra', champId: 143, icon: '/LOLicons/ZyraSquare.png', splash: '/Wallpapers/Zyra.jpg', desc: "Longing to take control of her fate, the ancient, dying plant Zyra transferred her consciousness into a human body for a second chance at life. Centuries ago, she and her kind dominated the Kumungu Jungle, using thorns and vines to consume any animal that set foot in their territory. As the years passed, the animal population steadily died off. Food became increasingly scarce, and Zyra could only stand by helplessly as the last of her kin withered away. She thought she would perish alone, until the appearance of an unwary sorceress presented her with an opportunity for salvation."},

    ])
  })
  .then(function() {
    console.log('seeded champion table....')
  })

module.exports = {
  User,
  Champion
}